### ISSUE TITLE
Use Groovy traits to better separate Omni RPCs from Bitcoin RPCs

### ISSUE THREAD

**Issue by msgilligan** [msgilligan/bitcoin-spock#29]
See the work in the branch [msgilligan-cliapi-traits](https://github.com/msgilligan/bitcoin-spock/tree/msgilligan-cliapi-traits)

**Comment by msgilligan** [comment]
Note: There seems to be a bug in Groovy 2.4.0 that occurs when the following lines are enabled in `BitcoinCLIAPI.groovy`:

    @SelfType(BitcoinClient)
    @CompileStatic

I've filed bug [GROOVY-7275](http://jira.codehaus.org/browse/GROOVY-7275) on Groovy JIRA.

I'm also seeing two issues in the current latest IntelliJ:
1. IntelliJ doesn't seem to recognize the `@SelfType(BitcoinClient)` annotation yet and as a result can't find the methods called from the superclass.
2. IntelliJ is complaining about default parameters with the message: "Default Initializers are not allowed in abstract methods"

**Comment by msgilligan** [comment]
Groovy bug [GROOVY-7275](http://jira.codehaus.org/browse/GROOVY-7275) is fixed in Groovy 2.4.1 and bitcoin-spock has been updated, so it may be time to try this again.

Although I'm thinking that it might be better if the "CLI" clients just warp the standard Java clients, rather than extend them, so traits may be less necessary.

**Comment by dexX7** [comment]
That's great to hear.

Point 2 seems to be an issue of IntelliJ, and using default values appears to work just fine, despite the error tag. Given there are quite a few methods that could be reduced and merged by using defaults, even though the error is a bit distracting.

**Comment by msgilligan** [comment]
I need to renew my IntelliJ subscription and upgrade to the latest version. If the IntelliJ problems continue, I'll report them as bugs.

**Comment by dexX7** [comment]
I'm currently using an [EAP build](https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP) of the v14.1 community edition, where the issue is still present.

**Comment by dexX7** [comment]
I noticed in the [latest EAP release notes](https://confluence.jetbrains.com/display/IDEADEV/IntelliJ+IDEA+14.1+140.2683.2+Release+Notes) "Good Groovy code red - traits with Generic" ([IDEA-134978](https://youtrack.jetbrains.com/issue/IDEA-134978)), however the issue related to default initializer values ("Default Initializers are not allowed in abstract methods") is still present.

**Comment by msgilligan** [comment]
This is complete, except for completing the CLI clients. I've opened Issue #64 for that work.
